// movie
export const GET_LIST_MOVIES = 'GET_LIST_MOVIES';
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const RESET_STATE_LOAD_MOVIE = 'RESET_STATE_LOAD_MOVIE';

// cinema
export const GET_THONG_TIN_LICH_CHIEU_PHIM = "GET_THONG_TIN_LICH_CHIEU_PHIM"
export const GET_THONG_TIN_CUM_RAP_THEO_HE_THONG = 'GET_THONG_TIN_CUM_RAP_THEO_HE_THONG'

//user
export const LOGIN_NGUOI_DUNG = "LOGIN_NGUOI_DUNG"
export const SET_USER_LOGIN = "SET_UBER_LOGIN"
export const GET_LIST_USER = "GET_LIST_USER"
export const GET_INFO_USER = "GET_INFO_USER"
export const RESET_LOAD_INFO_USER = "RESET_LOAD_INFO_USER"


//booking 
export const GET_DANH_SACH_PHONG_VE = "GET_DANH_SACH_PHONG_VE"
export const RESET_LOAD_DANH_SACH_PHONG_VE = "RESET_LOAD_DANH_SACH_PHONG_"
export const GHE_DANG_CHON = "GHE_DANG_CHON"
export const RESET_DANH_SACH_GHE = "RESET_DANH_SACH_GHE"
